require('colors');
const xmlEscape = require('xml-escape');

// TestFairy session data
const sessionData = require('../../session/sessionData.json');
sessionData.sessionUrl = 'https://automatic-tests.testfairy.com/projects/6852543-drawmeafairy/builds/9228222/sessions/4450931346';

// Interaction helpers
const DEFAULT_ACTIVITY_WAIT_UNTIL = {
    timeout: 5000,
    timeoutMsg: 'Activity not found!'
};

const LONG_PRESS_ACTION = [
    'longPress',
    { action: 'wait', ms: 2000 },
    'release'
];

function activityIsShown(activity) {
    return () => driver.getCurrentActivity().indexOf(activity) !== -1;
}

function selectorWithAndroidViewId(viewId, text, viewClassName) {
    let idBundle = sessionData.packageName + ':id/' + viewId;
    let textMatch = '';

    if (text && text.length > 0 && idBundle !== text && viewClassName != "android.widget.ImageButton") {
        textMatch = '.textStartsWith("' + xmlEscape(text) + '")';
    }

    const selector = 'new UiSelector().resourceId("' + idBundle + '")' + textMatch

    return 'android=' + selector;
}

function selectorWithTextInView(text, viewClassName) {
    return 'android=new UiSelector().textStartsWith("' + xmlEscape(text) + '").className("' + viewClassName + '")';
}

function selectorWithAccessibilityId(accessibilityId) {
    return `~${accessibilityId}`;
}

function selectorWithContentDescription(contentDescription) {
    // This is intentional and how webdriver.io works
    return selectorWithAccessibilityId(contentDescription);
}

// Test spec
describe((sessionData.appName + " - Android Test generated by TestFairy\n").magenta, () => {
    it("should simulate a session like ".magenta + sessionData.sessionUrl.magenta.underline, () => {

        // TF : TestFairy.begin(), time: 00:00
        console.log("\nTF : TestFairy.begin(), time: 00:00\n".magenta.underline);
        driver.pause(5000);

        // TF : 00:02
        console.log("\nTF : Clicked id/from_gallery, time: 00:02\n".magenta.underline);
        // $(selectorWithAndroidViewId('from_gallery', 'Open From Gallery', 'android.widget.Button')).click();
        // $(selectorWithAndroidViewId('from_gallery', 'Open From Gallery', 'android.widget.Button')).doubleClick();
        // $(selectorWithAndroidViewId('from_gallery', 'Open From Gallery', 'android.widget.Button')).touchAction(LONG_PRESS_ACTION);
        // $("//android.widget.RelativeLayout[1]/android.widget.Button[1]").click();
        // $(selectorWithTextInView('Open From Gallery', 'android.widget.Button')).click();
        // $(selectorWithAccessibilityId('Open from gallery')).click();
        // $(selectorWithContentDescription('Open from gallery')).click();

        // TF : 00:03
        console.log("\nTF : In com.testfairy.samples.drawmefairy.SelectPhotoActivity, time: 00:03\n".magenta.underline);
        driver.waitUntil(activityIsShown('.SelectPhotoActivity'), DEFAULT_ACTIVITY_WAIT_UNTIL);

        // driver.sendKeys("text");
        // driver.hideKeyboard();
        // driver.back();

    });
});
