// IMPORTANT : All further improvements into this file should be designed in a
// [platform, provider, framework]-agnostic manner!

import { Provider, Platform } from '../environment-types';
import { InputTestLine } from './input';
import { CheckpointTestLine } from './checkpoint';
import { UserInteractionTestLine } from './user-interaction';
import { ForegroundActivityTestLine } from './foreground-activity';
import { SessionMetaData, Test } from '../generator-types';

// Mandatory constructor for all test line visitors, must be conformed by the class object
export interface TestLineVisitorConstructor {
  new (visitor: TestLineVisitor | null): TestLineVisitor;
}

// Mandatory interface for all test line visitors, must be conformed by the instance object
export interface TestLineVisitor {
  /* These are visited once per code generation */
  visitInitialDocs(sessionUrl: string): void;
  visitImports(provider: Provider, sessionUrl: string): void;
  visitTestBegin(
    platform: Platform,
    provider: Provider,
    sessionUrl: string,
    sessionMetaData: SessionMetaData
  ): void;
  visitTestLimits(isComplete: boolean): void;
  visitAppLaunch(initialDelay: number): void;

  /* These are looped over in a polymorphic array and called multiple times */
  visitInputTestLine(line: InputTestLine): void;
  visitCheckpointTestLine(line: CheckpointTestLine): void;
  visitUserInteractionTestLine(line: UserInteractionTestLine): void;
  visitForegroundActivityTestLine(line: ForegroundActivityTestLine): void;

  /* This is visited once per code generation */
  visitTestEnd(): void;
}

// Globals for each test suite
export type GeneratorConfiguration = {
  test: Test;
  platform: Platform;
  provider: Provider;
  sessionUrl: string;
  initialDelay: number;
  sessionMetaData: SessionMetaData;
};

// Various types of test lines in the timeline
export type TestLine =
  | InputTestLine
  | CheckpointTestLine
  | UserInteractionTestLine
  | ForegroundActivityTestLine;

// Wrapper for test lines to accept visitors
export type TestLines = {
  testLines: TestLine[];
  accept(visitor: TestLineVisitor, config: GeneratorConfiguration): void;
};
export const createTestLines = (testLines: TestLine[]): TestLines => {
  const result = {
    testLines,
    accept: (visitor: TestLineVisitor, config: GeneratorConfiguration) => {
      visitor.visitInitialDocs(config.sessionUrl);
      visitor.visitImports(config.provider, config.sessionUrl);
      visitor.visitTestBegin(
        config.platform,
        config.provider,
        config.sessionUrl,
        config.sessionMetaData
      );
      visitor.visitTestLimits(config.test.incomplete);
      visitor.visitAppLaunch(config.initialDelay);

      result.testLines.forEach((testLine: TestLine) => {
        testLine.accept(visitor);
      });

      visitor.visitTestEnd();
    }
  };

  return result;
};

// A small utility to build a source code by appending valid strings
export type SourceCodeBuilder = {
  script: string;
  append(str: string): void;
};
export const createSourceCodeBuilder = (): SourceCodeBuilder => {
  const result = {
    script: '',
    append(str: string): void {
      result.script += str;
    }
  };

  return result;
};

/// A null-safe implementation for all test line visitors, derive from this as default
///
/// The code generated by this visitor can be deduced by reading visit methods
/// in this file from top to bottom.
export const BaseTestLinesVisitor: TestLineVisitorConstructor = class BaseTestLinesVisitor
  implements TestLineVisitor {
  visitor: TestLineVisitor | null;

  constructor(visitor: TestLineVisitor | null) {
    this.visitor = visitor;
  }

  visitInitialDocs(sessionUrl: string) {
    this.visitor?.visitInitialDocs(sessionUrl);
  }
  visitImports(provider: Provider, sessionUrl: string) {
    this.visitor?.visitImports(provider, sessionUrl);
  }
  visitTestBegin(
    platform: Platform,
    provider: Provider,
    sessionUrl: string,
    sessionMetaData: SessionMetaData
  ) {
    this.visitor?.visitTestBegin(
      platform,
      provider,
      sessionUrl,
      sessionMetaData
    );
  }
  visitTestLimits(isComplete: boolean) {
    this.visitor?.visitTestLimits(isComplete);
  }
  visitAppLaunch(initialDelay: number) {
    this.visitor?.visitAppLaunch(initialDelay);
  }
  visitInputTestLine(line: InputTestLine) {
    this.visitor?.visitInputTestLine(line);
  }
  visitCheckpointTestLine(line: CheckpointTestLine) {
    this.visitor?.visitCheckpointTestLine(line);
  }
  visitUserInteractionTestLine(line: UserInteractionTestLine) {
    this.visitor?.visitUserInteractionTestLine(line);
  }
  visitForegroundActivityTestLine(line: ForegroundActivityTestLine) {
    this.visitor?.visitForegroundActivityTestLine(line);
  }
  visitTestEnd() {
    this.visitor?.visitTestEnd();
  }
};

// A special implementation of test line visitor which can build strings as it visits test lines
export class TestLinesAppenderVisitor extends BaseTestLinesVisitor {
  indexJs: SourceCodeBuilder;

  constructor(visitor: TestLineVisitor | null, indexJs: SourceCodeBuilder) {
    super(visitor);

    this.indexJs = indexJs;
  }

  append(str: string): void {
    this.indexJs.append(str);
  }
}
